version: "3.8"
#111
networks:
  kafka_network:

x-check-ports: &check-ports ./bin/check-ports:/bin/check-ports
x-service-template: &template
  restart: on-failure
  networks:
    - kafka_network
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 10
  volumes:
    - *check-ports

services:
  manager:
    <<: *template
    image: neshkeev/bash-notebook
    hostname: &mname manager
    container_name: *mname
    command: /usr/local/bin/entrypoint
    healthcheck:
      <<: *hc
      test: /bin/check-ports 8888
    ports:
      - "8888:8888"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - *check-ports
      - ./ssh:/home/jovyan/.ssh
      - ./bin/manager-entrypoint:/usr/local/bin/entrypoint:777
      - ./bin/manager.bashrc:/home/jovyan/.bashrc
      - ./src/kafka-basics.ipynb:/home/jovyan/work/kafka-basics.ipynb
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      DIND_HOST: dind
      NOTEBOOK_ARGS: --NotebookApp.token='' --NotebookApp.password=''
      RESTARTABLE: yes

  zookeeper:
    <<: *template
    image: zookeeper:3.8
    hostname: &zname zookeeper
    container_name: *zname
    healthcheck:
      <<: *hc
      test: /bin/check-ports 2181

  kafka:
    <<: *template
    build:
      context: .
      dockerfile: local/Dockerfile_kafka
    hostname: &kname kafka
    container_name: *kname
    healthcheck:
      <<: *hc
      # kafka broker and ssh ports should be open
      test: /bin/check-ports 9092 2222
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: true

  redpanda:
    <<: *template
    image: docker.redpanda.com/redpandadata/console:v2.2.4
    hostname: &rname redpanda
    container_name: *rname
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      <<: *hc
      test: sh /bin/check-ports 8080
    environment:
      KAFKA_BROKERS: kafka:9092

  dind:
    <<: *template
    build:
      context: .
      dockerfile: local/Dockerfile_dind
    hostname: &name dind
    container_name: *name
    healthcheck:
      <<: *hc
      test: sh /bin/check-ports 2222
    privileged: true
    volumes:
      - *check-ports
      - ./docker-compose.yml:/root/${CURRENT_DIR_NAME:-kafka-exercises}/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CURRENT_DIR_NAME: ${CURRENT_DIR_NAME:-kafka-exercises}
